# Generated by Django 6.0.4 on 2026-05-03 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='reorder_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
