# Generated by Django 6.0.4 on 2026-05-03 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_stockitem_reorder_level_supplier_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('WALK_IN', 'Walk-In'), ('WHOLESALE', 'Wholesale'), ('SCHEME', 'Scheme Pickup')], default='WALK_IN', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('customer_name', models.CharField(default='Walk-in', max_length=100)),
                ('member_nin', models.CharField(blank=True, max_length=14, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.stockitem')),
            ],
        ),
    ]
