# Generated by Django 6.0.4 on 2026-05-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
    ]
