# Generated by Django 6.0.4 on 2026-05-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_item_salaryearner_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STOCK', 'Stock Manager'), ('CASHIER', 'Cashier'), ('SALES', 'Sales Person')], default='CASHIER', max_length=20),
        ),
    ]
