# Generated by Django 6.0.5 on 2026-05-18 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_customuser_phone_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='product',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryearner',
            name='credit_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryearner',
            name='nin_number',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Validation Error: NIN must contain exactly 14 characters following the official NIRA layout framework.', regex='^[A-Z]{2}\\d{2}[A-Z\\d]{2}\\d{7}[A-Z\\d]{1}$')]),
        ),
        migrations.AlterField(
            model_name='salaryearner',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Validation Error: Provide a valid Ugandan phone line (e.g., 0772000000 or +256752000000).', regex='^(?:\\+256|256|0)?(7\\d{8})$')]),
        ),
        migrations.AlterField(
            model_name='salaryearner',
            name='target_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
