# Generated by Django 6.0.4 on 2026-05-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_sale_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryEarner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_name', models.CharField(max_length=100)),
                ('nin_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.stockitem')),
                ('salary_earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.salaryearner')),
            ],
        ),
    ]
