# Generated by Django 6.0.4 on 2026-05-05 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_salaryearner_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryearner',
            name='workplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.stockitem'),
            preserve_default=False,
        ),
    ]
