# Generated by Django 6.0.5 on 2026-05-19 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_deposit_product_remove_deposit_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Validation Error: Provide a valid Ugandan phone line matching 07... or +2567... (9 to 13 digits).', regex='^(?:\\+256|256|0)?(7\\d{8})$')]),
        ),
        migrations.AlterField(
            model_name='salaryearner',
            name='nin_number',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Validation Error: NIN must contain exactly 14 uppercase alphanumeric characters matching NIRA framework profiles.', regex='^[A-Z0-9]{14}$')]),
        ),
        migrations.AlterField(
            model_name='salaryearner',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Validation Error: Provide a valid Ugandan phone line matching 07... or +2567... (9 to 13 digits).', regex='^(?:\\+256|256|0)?(7\\d{8})$')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='member_nin',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Validation Error: NIN must contain exactly 14 uppercase alphanumeric characters matching NIRA framework profiles.', regex='^[A-Z0-9]{14}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Validation Error: Provide a valid Ugandan phone line matching 07... or +2567... (9 to 13 digits).', regex='^(?:\\+256|256|0)?(7\\d{8})$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
