# Generated by Django 6.0.5 on 2026-05-19 06:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_category_options_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryearner',
            name='nin_number',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Validation Error: NIN must start with CF or CM, followed by 8–10 digits, and end with 2–4 uppercase letters.', regex='^(CF|CM)\\d{8,10}[A-Z]{2,4}$')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='member_nin',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Validation Error: NIN must start with CF or CM, followed by 8–10 digits, and end with 2–4 uppercase letters.', regex='^(CF|CM)\\d{8,10}[A-Z]{2,4}$')]),
        ),
    ]
