# Generated by Django 6.0.4 on 2026-05-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_salaryearner_workplace_alter_deposit_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
